name: Bug report
description: Report an issue with the modpack.
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Before reporting an issue, [please search](https://github.com/Dseelis/Steamcreate2/issues) to ensure it has not already been reported.

- type: input
  attributes:
    label: Modpack version
    description: What version of the modpack are you using?
  validations:
    required: true

- type: dropdown
  attributes:
    label: Launcher
    description: Which launcher are you using?
    options:
      - CurseForge App
      - Modrinth App
      - Prism Launcher
      - MultiMC
      - Other
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce and Additional context
    description: Provide a step-by-step guide on how to reproduce the issue.
  validations:
    required: true
