#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Mar 04 17:07:23 EET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=11
shaderPack=ComplementaryUnbound_r5.6.1 + Clrwl_1.0.4.zip
