#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Feb 23 19:38:06 EET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=11
shaderPack=ComplementaryUnbound_r5.6.1 + Clrwl_1.0.4.zip
