#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 15 10:20:40 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=11
shaderPack=
